spring.application.name=videojuegos
# Base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:tiendadb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola web de H2 (para ver la BD en el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate crea/actualiza las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true