INSERT INTO videojuego (titulo, descripcion, imagen_url) VALUES
('GTA VI', 'La ciudad de Vice City esconde una red de crimen organizado que crece sin control. Tu misión es desarrollar un juego de mundo abierto inspirado en el universo de GTA VI, donde los jugadores puedan explorar la ciudad libremente, completar misiones y vivir historias de acción y crimen.', 'https://colombiajuegosdigitales.com/wp-content/uploads/2026/06/Grand-Theft-Auto-VI-PS5.webp'),
('Uncharted 4', 'Un tesoro pirata legendario ha permanecido oculto durante siglos, esperando ser encontrado. Tu misión es desarrollar un juego de aventuras y acción inspirado en el universo de Uncharted, donde los jugadores puedan explorar ruinas antiguas, resolver acertijos y enfrentarse a peligrosos rivales en busca del tesoro.', 'https://juegosdigitalescolombia.com/files/images/thumbs/productos_300x400_1576686876-uncharted-4-el-desenlace-del-ladron-ps4.jpg'),
('Assassin''s Creed Black Flag', 'Los mares del Caribe están llenos de riquezas, piratas y secretos de la Orden de los Asesinos. Tu misión es desarrollar un juego de acción y navegación inspirado en el universo de Assassin''s Creed, donde los jugadores puedan comandar su propio barco, abordar naves enemigas y descubrir conspiraciones ocultas.', 'https://juegosdigitalescolombia.com/files/images/productos/1783626737-assassins-creed-black-flag-resynced-ps5-0.webp'),
('Fortnite', 'Cien jugadores caen sobre una isla y solo uno puede quedar en pie. Tu misión es desarrollar un juego de batalla real inspirado en el universo de Fortnite, donde los jugadores puedan construir estructuras, recolectar recursos y enfrentarse a otros participantes hasta ser el último sobreviviente.', 'https://m.media-amazon.com/images/I/917JLu3S8DL._AC_UF1000,1000_QL80_.jpg');

INSERT INTO videojuego (titulo, descripcion, imagen_url) VALUES
('Naruto', 'El maestro Kakashi ha organizado un torneo entre los ninjas más poderosos de Konoha. Tu misión es desarrollar un juego de combate por turnos inspirado en el universo de Naruto, donde los jugadores puedan seleccionar su personaje favorito y enfrentarse a otros ninjas en batallas estratégicas.', 'https://juegosdigitalescolombia.com/files/images/productos/1499274233-naruto-shippuden-ultimate-ninja-storm-4.jpg'),
('Street Fighter', 'Un torneo mundial de artes marciales ha reunido a los mejores luchadores del planeta. Tu misión es desarrollar un juego de combate uno contra uno inspirado en el universo de Street Fighter, donde los jugadores puedan elegir entre distintos luchadores con movimientos y golpes especiales únicos, y competir por el título de campeón mundial.', 'https://juegosdigitalescolombia.com/files/images/productos/1745942814-street-fighter-6-fighters-edition-years-1-2-ps4-pre-orden-0.webp'),
('Mortal Kombat', 'Los guerreros de los reinos han sido convocados a un torneo mortal donde solo el más fuerte sobrevive. Tu misión es desarrollar un juego de combate inspirado en el universo de Mortal Kombat, donde los jugadores puedan seleccionar a su luchador, dominar combos brutales y enfrentarse en batallas hasta la fatalidad final.', 'https://juegosdigitalescolombia.com/files/images/productos/1570816839-mortal-kombat-11-ps4.png'),
('One Piece', 'El Rey de los Piratas ha dejado un tesoro legendario escondido en algún lugar del Grand Line. Tu misión es desarrollar un juego de aventuras inspirado en el universo de One Piece, donde los jugadores puedan formar su tripulación, explorar islas y enfrentarse a otros piratas en la búsqueda del One Piece.', 'https://juegosdigitalescolombia.com/files/images/productos/1625180353-one-piece-world-seeker-ps5.jpg');

INSERT INTO videojuego (titulo, descripcion, imagen_url) VALUES
('God of War Ragnarök', 'Kratos y Atreus recorren los nueve reinos mientras intentan evitar el destino anunciado por el Ragnarök. Un juego de acción y aventura con combates intensos, exploración y una historia épica.', 'https://upload.wikimedia.org/wikipedia/en/e/ee/God_of_War_Ragnar%C3%B6k_cover.jpg'),
('Marvel''s Spider-Man 2', 'Peter Parker y Miles Morales unen sus fuerzas para proteger Nueva York de nuevas amenazas. Un juego de acción de mundo abierto con balanceo por la ciudad, poderes y combates espectaculares.', 'https://upload.wikimedia.org/wikipedia/en/0/0f/SpiderMan2PS5BoxArt.jpeg'),
('The Last of Us Part II', 'Años después de los acontecimientos originales, Ellie emprende un viaje marcado por la pérdida, la venganza y decisiones difíciles en un mundo devastado.', 'https://upload.wikimedia.org/wikipedia/en/4/4f/TLOU_P2_Box_Art_2.png'),
('Ghost of Tsushima', 'Un samurái debe proteger la isla de Tsushima durante la invasión mongola y encontrar una nueva forma de luchar para salvar a su pueblo.', 'https://upload.wikimedia.org/wikipedia/en/b/b6/Ghost_of_Tsushima.jpg'),
('Gran Turismo 7', 'Compite en circuitos legendarios y descubre una colección de vehículos icónicos en una experiencia de conducción detallada para los amantes del automovilismo.', 'https://upload.wikimedia.org/wikipedia/en/1/14/Gran_Turismo_7_cover_art.jpg'),
('Horizon Forbidden West', 'Aloy explora un Oeste Prohibido lleno de máquinas colosales, tribus desconocidas y misterios que amenazan el futuro de la humanidad.', 'https://upload.wikimedia.org/wikipedia/en/6/69/Horizon_Forbidden_West_cover_art.jpg'),
('Bloodborne', 'Adéntrate en la ciudad de Yharnam, donde una antigua enfermedad ha convertido a sus habitantes en criaturas aterradoras. Sobrevive a sus calles y descubre sus oscuros secretos.', 'https://upload.wikimedia.org/wikipedia/en/6/68/Bloodborne_Cover_Wallpaper.jpg'),
('Ratchet & Clank: Rift Apart', 'Ratchet, Clank y Rivet saltan entre dimensiones para detener a un enemigo que amenaza con destruir todos los mundos. Acción, plataformas y humor en una aventura interdimensional.', 'https://upload.wikimedia.org/wikipedia/en/a/a3/Ratchet_%26_Clank_-_Rift_Apart.png');